import { createFileRoute, Link } from "@tanstack/react-router";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BookingCta, Eyebrow, Reveal } from "@/components/site-elements";
import { images, services } from "@/lib/site-content";
const items=[...services.map((s,i)=>({...s,cat:["Suits","Weddings","Suits","Outerwear"][i]??"Suits"})),{id:"bridal-fitting",title:"The Bridal Fitting",note:"A hem shaped for movement.",image:images.bridalFitting,alt:"Wedding dress hem pinned during a bridal fitting in Birmingham",cat:"Weddings"},{id:"lace-work",title:"Lace & Beadwork",note:"Intricate detail, preserved by hand.",image:images.laceDetail,alt:"Fine bridal lace and beadwork being altered by hand",cat:"Fabrics"},{id:"bridesmaids",title:"Bridesmaid Finish",note:"A balanced fit across the bridal party.",image:images.bridesmaidFitting,alt:"Sage bridesmaid dresses being adjusted in the atelier",cat:"Weddings"},{id:"fabric",title:"Cloth & Finish",note:"The material sets the tone.",image:images.fabric,alt:"Camel wool and blush silk with brass shears",cat:"Fabrics"},{id:"shirt",title:"Shirting Study",note:"Collar, cuff and line considered together.",image:images.hero,alt:"Tailor fitting a client in a Birmingham atelier",cat:"Shirts"}];
export const Route=createFileRoute("/gallery")({head:()=>({meta:[{title:"Bespoke Suit Gallery Birmingham | The Tailor Lady"},{name:"description",content:"Explore bespoke suits, wedding tailoring, outerwear and fine fabrics created by a Birmingham city centre tailor."},{property:"og:title",content:"Bespoke Suit Gallery Birmingham | The Tailor Lady"},{property:"og:description",content:"A considered gallery of bespoke and made to measure commissions in Birmingham."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/gallery"}]}),component:Gallery});
function Gallery(){const [filter,setFilter]=useState("All");const [active,setActive]=useState<(typeof items)[number]|null>(null);const shown=filter==="All"?items:items.filter(x=>x.cat===filter);return <><section className="page-wrap grid min-h-[72dvh] gap-8 pb-16 pt-36 md:grid-cols-[1.2fr_.8fr] md:items-end"><div><Eyebrow>Selected commissions</Eyebrow><h1 className="mt-5 font-display text-6xl leading-[.92] md:text-8xl">A gallery of bespoke tailoring in Birmingham.</h1></div><div className="border-l border-border pl-6"><span className="inline-block bg-ink px-4 py-2 text-xs uppercase tracking-[.16em] text-primary-foreground">800+ project images</span><p className="mt-5 leading-7 text-muted-foreground">From first cloth choice to final press: close studies of shape, detail and personal style.</p></div></section><section className="bg-secondary px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-wrap gap-2" role="group" aria-label="Filter gallery">{["All","Suits","Shirts","Outerwear","Weddings","Fabrics"].map(f=><Button key={f} variant={filter===f?"editorial":"outline"} onClick={()=>setFilter(f)}>{f}</Button>)}</div><motion.div layout className="columns-1 gap-4 md:columns-2 lg:columns-3"><AnimatePresence>{shown.map((item,i)=><motion.button layout key={item.id} aria-label={`View ${item.title}`} onClick={()=>setActive(item)} initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.96}} transition={{delay:i*.05}} className="mb-4 block w-full break-inside-avoid overflow-hidden bg-card text-left"><img src={item.image} alt={item.alt} width={1200} height={1504} loading="lazy" className={`w-full object-cover ${i%3===0?"aspect-[4/5]":"aspect-square"}`}/><span className="block p-5"><span className="font-display text-2xl">{item.title}</span><span className="mt-1 block text-xs uppercase tracking-[.14em] text-muted-foreground">{item.cat}</span></span></motion.button>)}</AnimatePresence></motion.div></div></section>
<section className="page-wrap py-24"><Eyebrow>Case studies</Eyebrow><h2 className="mt-4 font-display text-5xl">From conversation to cloth.</h2><div className="mt-12 grid gap-12 md:grid-cols-3">{["A modern city wedding","A working wardrobe","An evening signature"].map((x,i)=><Reveal key={x}><p className="text-xs uppercase tracking-[.16em]">0{i+1}</p><h3 className="mt-4 font-display text-3xl">{x}</h3><ol className="mt-5 space-y-3 border-l border-border pl-5 text-sm text-muted-foreground"><li>Consultation & direction</li><li>Measurement & basted fitting</li><li>Final fitting & finish</li></ol></Reveal>)}</div><div className="mt-12 flex flex-wrap gap-4"><BookingCta/><Button asChild variant="outline"><Link to="/services">Explore services</Link></Button></div></section>
<AnimatePresence>{active&&<motion.div className="fixed inset-0 z-[80] grid place-items-center bg-ink/95 p-5" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true" aria-label={active.title} onClick={()=>setActive(null)}><Button variant="ivory" size="icon" className="absolute right-5 top-5 min-h-11 min-w-11 rounded-full" aria-label="Close image"><X/></Button><motion.figure initial={{scale:.94}} animate={{scale:1}} onClick={e=>e.stopPropagation()} className="max-h-[88dvh] max-w-4xl"><img src={active.image} alt={active.alt} className="max-h-[78dvh] w-auto object-contain"/><figcaption className="mt-3 text-center font-display text-2xl text-primary-foreground">{active.title}</figcaption></motion.figure></motion.div>}</AnimatePresence></>}
