import { createFileRoute, Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { HomePreloader } from "@/components/home-preloader";
import { BookingCta, Eyebrow, Reveal, SectionHeading } from "@/components/site-elements";
import { Button } from "@/components/ui/button";
import { images, services } from "@/lib/site-content";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Wedding Dress Alterations Birmingham | The Tailor Lady"},{name:"description",content:"Wedding dress and bridesmaid dress alterations in Birmingham city centre, alongside clothing alterations, tailoring and dry cleaning."},{property:"og:title",content:"Wedding Dress Alterations Birmingham | The Tailor Lady"},{property:"og:description",content:"Expert bridal, bridesmaid and clothing alterations in Birmingham city centre."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"},{rel:"preload",as:"image",href:images.hero,fetchPriority:"high"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":["LocalBusiness","ProfessionalService","ClothingStore"],name:"The Tailor Lady",description:"Wedding dress, bridesmaid dress and clothing alterations in Birmingham city centre.",telephone:"+447342477032",address:{"@type":"PostalAddress",addressLocality:"Birmingham",addressCountry:"GB"},areaServed:"Birmingham",priceRange:"££",openingHoursSpecification:[{"@type":"OpeningHoursSpecification",dayOfWeek:["Monday","Tuesday","Wednesday","Thursday","Friday"],opens:"10:00",closes:"18:30"},{"@type":"OpeningHoursSpecification",dayOfWeek:"Saturday",opens:"10:00",closes:"17:00"}],hasOfferCatalog:{"@type":"OfferCatalog",name:"Alteration services",itemListElement:["Wedding dress alterations","Bridesmaid dress alterations","General clothing alterations","Tailoring","Dry cleaning"]}})}]}),component:Home});

function Home(){return <><HomePreloader/>
  <section className="relative min-h-dvh overflow-hidden bg-ink text-primary-foreground"><motion.img src={images.hero} alt="Tailor at work in a Birmingham city centre atelier" className="absolute inset-0 size-full object-cover" width={1600} height={1104} initial={{scale:1.06}} animate={{scale:1}} transition={{duration:1.8}}/><div className="absolute inset-0 bg-hero-overlay"/><div className="relative mx-auto flex min-h-dvh max-w-7xl flex-col justify-end px-5 pb-20 pt-32 md:px-10 md:pb-24"><Eyebrow light>Bridal alterations · Birmingham</Eyebrow><h1 className="mt-5 max-w-5xl font-display text-6xl leading-[.88] md:text-8xl lg:text-[7.6rem]">The perfect dress.<br/><em className="text-accent">Made truly yours.</em></h1><div className="mt-7 flex max-w-2xl flex-col items-start justify-between gap-7 md:flex-row md:items-end"><p className="max-w-md text-base leading-7 text-primary-foreground/80">Specialist wedding dress and bridesmaid alterations in Birmingham city centre, shaped around comfort, movement and confidence.</p><BookingCta dark/></div><ArrowDown className="absolute bottom-7 right-8 animate-bounce" aria-hidden="true"/></div></section>
  <section className="relative z-20 bg-background px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Alterations & tailoring" title="Beautiful clothes, fitted for your life." body="Bridal is at the heart of the atelier, supported by considered alterations, tailoring and professional garment care."/><div className="mt-14 grid gap-4 md:grid-cols-12">{services.map((s,i)=><Reveal key={s.id} className={i===0||i===3?"md:col-span-7":"md:col-span-5"}><Link to="/services" hash={s.id} className="group block overflow-hidden bg-card"><div className={i===0||i===3?"aspect-[16/11] overflow-hidden":"aspect-[4/5] overflow-hidden"}><img src={s.image} alt={s.alt} width={1200} height={1504} loading="lazy" className="image-hover size-full object-cover"/></div><div className="flex items-end justify-between p-5"><div><h3 className="font-display text-3xl">{s.title}</h3><p className="mt-1 text-sm text-muted-foreground">{s.note}</p></div><ArrowUpRight className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></div></Link></Reveal>)}</div><div className="mt-12"><BookingCta/></div></div></section>
  <section className="relative overflow-hidden bg-ink text-primary-foreground"><div className="mx-auto grid min-h-[85dvh] max-w-[100rem] lg:grid-cols-12"><div className="relative min-h-[34rem] overflow-hidden lg:col-span-7"><img src={images.wedding} alt="Wedding dress tailoring detail for a bridal fitting" width={1200} height={1504} loading="lazy" className="absolute inset-0 size-full object-cover opacity-80"/><div className="absolute inset-0 bg-process-image"/><p className="absolute bottom-7 left-7 max-w-xs text-xs uppercase tracking-[.18em] text-primary-foreground/70 md:bottom-10 md:left-10">Wedding dresses · Bridesmaid dresses · Birmingham</p></div><div className="flex flex-col justify-center px-7 py-20 lg:col-span-5 lg:px-14"><Eyebrow light>Bridal is our focus</Eyebrow><h2 className="mt-5 font-display text-5xl leading-[.95] md:text-7xl">Considered from first pin to final fitting.</h2><p className="mt-7 max-w-lg leading-8 text-primary-foreground/65">From a clean hem to intricate lace, beadwork, bodice reshaping and train bustles, every alteration is assessed around the construction of your dress and how you want to move through the day.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="ivory" size="lg"><Link to="/alterations" hash="prices">View bridal prices <ArrowUpRight/></Link></Button><BookingCta dark/></div></div></div></section>
  <section className="bg-background px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><Eyebrow>Beyond the bridal suite</Eyebrow><h2 className="mt-5 font-display text-5xl leading-none md:text-7xl">Care for the rest of your wardrobe.</h2></div><div className="grid gap-px bg-border lg:col-span-8 md:grid-cols-2">{[["General alterations","Dresses, skirts, trousers, jeans, shirts, jackets and coats — refined for fit, length and everyday ease."],["Dry cleaning","Professional care for tailoring, outerwear, dresses, wedding dresses and specialist pieces."],["Bridesmaid dresses","Hems, side seams and shoulder adjustments for a beautifully balanced bridal party."],["Personal assessment","Complex construction, delicate cloth and involved repairs are assessed individually before work begins."]].map(([title,copy],i)=><article key={title} className={i===0?"bg-ink p-8 text-primary-foreground md:p-10":"bg-card p-8 md:p-10"}><p className="text-xs uppercase tracking-[.18em] text-accent">0{i+1}</p><h3 className="mt-9 font-display text-4xl">{title}</h3><p className={i===0?"mt-4 leading-7 text-primary-foreground/65":"mt-4 leading-7 text-muted-foreground"}>{copy}</p></article>)}</div></div><div className="mt-14 border-t border-border pt-8"><BookingCta/></div></div></section>
</>}